// Mock events data for static deployment
// 20+ events covering all categories

export const mockEvents = [
  // On-Stage Events
  {
    id: 1,
    name: "Classical Dance Recital",
    description: "Experience the grace and elegance of classical Indian dance forms. A mesmerizing performance showcase.",
    category: "On-Stage",
    entryFee: 500,
    prizeFirst: 5000,
    prizeSecond: 3000,
    teamSize: "Group",
    venue: "Main Auditorium",
    date: "5th March",
  },
  {
    id: 2,
    name: "Modern Music Festival",
    description: "Contemporary music performances from emerging artists across genres and styles.",
    category: "On-Stage",
    entryFee: 1000,
    prizeFirst: 10000,
    prizeSecond: 6000,
    teamSize: "Group",
    venue: "Open Grounds",
    date: "5th March",
  },
  {
    id: 3,
    name: "Fashion Show 2026",
    description: "Showcase of latest fashion trends and designer collections by student designers.",
    category: "On-Stage",
    entryFee: 750,
    prizeFirst: 8000,
    prizeSecond: 5000,
    teamSize: "Group",
    venue: "Fashion Arena",
    date: "6th March",
  },
  {
    id: 4,
    name: "Stand-up Comedy Night",
    description: "Hilarious performances by top comedians bringing laughter and entertainment.",
    category: "On-Stage",
    entryFee: 300,
    prizeFirst: 3000,
    prizeSecond: 1500,
    teamSize: "Solo",
    venue: "Comedy Club",
    date: "5th March",
  },
  {
    id: 5,
    name: "Indian Classical Singing",
    description: "Soulful renditions of classical Indian ragas and devotional music.",
    category: "On-Stage",
    entryFee: 600,
    prizeFirst: 6000,
    prizeSecond: 4000,
    teamSize: "Solo",
    venue: "Concert Hall",
    date: "6th March",
  },
  {
    id: 6,
    name: "Theater Play - Mahabharat",
    description: "Epic retelling of the Mahabharat in theatrical format with modern interpretation.",
    category: "On-Stage",
    entryFee: 800,
    prizeFirst: 7000,
    prizeSecond: 4500,
    teamSize: "Group",
    venue: "Grand Theater",
    date: "6th March",
  },
  {
    id: 7,
    name: "Bollywood Dance Competition",
    description: "Show your Bollywood moves and compete with other dancers for amazing prizes.",
    category: "On-Stage",
    entryFee: 400,
    prizeFirst: 4000,
    prizeSecond: 2500,
    teamSize: "Group",
    venue: "Studio A",
    date: "5th March",
  },
  {
    id: 8,
    name: "Band Battle",
    description: "Battle of the bands featuring student rock and pop bands from across college.",
    category: "On-Stage",
    entryFee: 700,
    prizeFirst: 8000,
    prizeSecond: 5000,
    teamSize: "Group",
    venue: "Main Auditorium",
    date: "6th March",
  },
  {
    id: 9,
    name: "Poetry Slam",
    description: "Express yourself through powerful and thought-provoking poetry recitations.",
    category: "On-Stage",
    entryFee: 200,
    prizeFirst: 2000,
    prizeSecond: 1000,
    teamSize: "Solo",
    venue: "Literary Hall",
    date: "5th March",
  },
  {
    id: 10,
    name: "Debate Championship",
    description: "Intellectual battle of ideas on contemporary and historical topics.",
    category: "On-Stage",
    entryFee: 300,
    prizeFirst: 3000,
    prizeSecond: 1500,
    teamSize: "Duet",
    venue: "Conference Room",
    date: "6th March",
  },
  // On-Ground Events
  {
    id: 11,
    name: "Street Food Festival",
    description: "Delicious street food from across India with vendor stalls and tasting experiences.",
    category: "On-Ground",
    entryFee: 200,
    prizeFirst: 2000,
    prizeSecond: 1000,
    teamSize: "Solo",
    venue: "Festival Grounds",
    date: "5th March",
  },
  {
    id: 12,
    name: "Gaming Tournament",
    description: "Competitive gaming event with multiple games - PUBG, CS:GO, and more.",
    category: "On-Ground",
    entryFee: 500,
    prizeFirst: 5000,
    prizeSecond: 3000,
    teamSize: "Group",
    venue: "Gaming Arena",
    date: "5th March",
  },
  {
    id: 13,
    name: "Treasure Hunt",
    description: "Exciting treasure hunt across campus with riddles, challenges and prizes.",
    category: "On-Ground",
    entryFee: 100,
    prizeFirst: 1500,
    prizeSecond: 800,
    teamSize: "Group",
    venue: "Entire Campus",
    date: "6th March",
  },
  {
    id: 14,
    name: "Sports Day",
    description: "Fun sports competitions including cricket, badminton, volleyball and more.",
    category: "On-Ground",
    entryFee: 250,
    prizeFirst: 2500,
    prizeSecond: 1500,
    teamSize: "Group",
    venue: "Sports Ground",
    date: "5th March",
  },
  {
    id: 15,
    name: "Photography Contest",
    description: "Showcase your photography skills. Categories: Nature, Portrait, Street, Abstract.",
    category: "On-Ground",
    entryFee: 150,
    prizeFirst: 1500,
    prizeSecond: 800,
    teamSize: "Solo",
    venue: "Gallery Hall",
    date: "6th March",
  },
  // Fine Arts
  {
    id: 16,
    name: "Painting Exhibition",
    description: "Display and judging of paintings across various mediums and styles.",
    category: "Fine Arts",
    entryFee: 100,
    prizeFirst: 1000,
    prizeSecond: 500,
    teamSize: "Solo",
    venue: "Art Gallery",
    date: "5th March",
  },
  {
    id: 17,
    name: "Sculpture Workshop",
    description: "Learn basic sculpture techniques from experienced artists in this hands-on workshop.",
    category: "Fine Arts",
    entryFee: 300,
    prizeFirst: null,
    prizeSecond: null,
    teamSize: "Solo",
    venue: "Art Studio",
    date: "5th March",
  },
  {
    id: 18,
    name: "Digital Art Showcase",
    description: "Display of digital art, animations, graphics and visual effects by student artists.",
    category: "Fine Arts",
    entryFee: 200,
    prizeFirst: 2000,
    prizeSecond: 1000,
    teamSize: "Solo",
    venue: "Digital Lab",
    date: "6th March",
  },
  // Literary
  {
    id: 19,
    name: "Creative Writing Contest",
    description: "Write your best short story, essay or poem and compete with fellow writers.",
    category: "Literary",
    entryFee: 100,
    prizeFirst: 1500,
    prizeSecond: 800,
    teamSize: "Solo",
    venue: "Library",
    date: "5th March",
  },
  {
    id: 20,
    name: "Book Club Discussion",
    description: "Discuss and share insights about contemporary and classic literature.",
    category: "Literary",
    entryFee: 50,
    prizeFirst: null,
    prizeSecond: null,
    teamSize: "Solo",
    venue: "Reading Room",
    date: "6th March",
  },
  {
    id: 21,
    name: "News Quiz",
    description: "Test your knowledge of current events and general awareness.",
    category: "Literary",
    entryFee: 150,
    prizeFirst: 1500,
    prizeSecond: 800,
    teamSize: "Duet",
    venue: "Classroom Block",
    date: "5th March",
  },
  {
    id: 22,
    name: "Storytelling Night",
    description: "Share your unique stories and listen to tales from your peers.",
    category: "Literary",
    entryFee: 100,
    prizeFirst: 1000,
    prizeSecond: 500,
    teamSize: "Solo",
    venue: "Amphitheater",
    date: "6th March",
  },
  // Gaming
  {
    id: 23,
    name: "Mobile Gaming Championship",
    description: "Compete in popular mobile games - PUBG Mobile, Call of Duty Mobile.",
    category: "Gaming",
    entryFee: 400,
    prizeFirst: 4000,
    prizeSecond: 2500,
    teamSize: "Solo",
    venue: "Gaming Arena",
    date: "5th March",
  },
  {
    id: 24,
    name: "Board Game Tournament",
    description: "Classic board games competition - Chess, Checkers, Scrabble and more.",
    category: "Gaming",
    entryFee: 200,
    prizeFirst: 2000,
    prizeSecond: 1000,
    teamSize: "Solo",
    venue: "Recreation Hall",
    date: "6th March",
  },
];
