// Mock events data for static deployment
// Complete event list with accurate categories, fees and prizes

export const mockEvents = [
  // === ON-STAGE EVENTS - DANCE ===
  {
    id: 1,
    name: "Dance - Solo",
    description: "Solo dance performance showcasing your talent and choreography skills.",
    category: "On-Stage",
    entryFee: 100,
    prizeFirst: 1000,
    prizeSecond: 800,
    teamSize: "Solo",
    venue: "Main Auditorium",
    date: "5th March",
  },
  {
    id: 2,
    name: "Dance - Duet",
    description: "Duet dance performance with synchronized movements and partner choreography.",
    category: "On-Stage",
    entryFee: 150,
    prizeFirst: 1000,
    prizeSecond: 800,
    teamSize: "Duet",
    venue: "Main Auditorium",
    date: "5th March",
  },
  {
    id: 3,
    name: "Dance - Group",
    description: "Group dance performance with dynamic movements and ensemble coordination.",
    category: "On-Stage",
    entryFee: 500,
    prizeFirst: 3000,
    prizeSecond: 2000,
    teamSize: "Group",
    venue: "Main Auditorium",
    date: "5th March",
  },
  // === ON-STAGE EVENTS - SINGING ===
  {
    id: 4,
    name: "Singing - Solo",
    description: "Solo singing performance showcasing your vocal abilities and musical talent.",
    category: "On-Stage",
    entryFee: 100,
    prizeFirst: 1000,
    prizeSecond: 800,
    teamSize: "Solo",
    venue: "Concert Hall",
    date: "5th March",
  },
  {
    id: 5,
    name: "Singing - Duet",
    description: "Duet singing with harmonious blend and complementary vocals.",
    category: "On-Stage",
    entryFee: 150,
    prizeFirst: 1000,
    prizeSecond: 800,
    teamSize: "Duet",
    venue: "Concert Hall",
    date: "5th March",
  },
  // === ON-STAGE EVENTS - FASHION ===
  {
    id: 6,
    name: "Fashion Show",
    description: "Display your fashion sense and creativity through a spectacular fashion show.",
    category: "On-Stage",
    entryFee: 1500,
    prizeFirst: 7000,
    prizeSecond: 4000,
    teamSize: "Group",
    venue: "Fashion Arena",
    date: "6th March",
  },
  // === ON-GROUND EVENTS ===
  {
    id: 7,
    name: "Antakshari",
    description: "Group singing game where teams continue songs starting with last letter.",
    category: "On-Ground",
    entryFee: 250,
    prizeFirst: 1500,
    prizeSecond: 1000,
    teamSize: "Group",
    venue: "Open Grounds",
    date: "5th March",
  },
  {
    id: 8,
    name: "Flashmob",
    description: "Surprise dance performance by large group in public space.",
    category: "On-Ground",
    entryFee: 100,
    prizeFirst: 1500,
    prizeSecond: 1000,
    teamSize: "Group",
    venue: "Campus Grounds",
    date: "6th March",
  },
  {
    id: 9,
    name: "Treasure Hunt",
    description: "Team competition solving riddles and completing challenges across campus.",
    category: "On-Ground",
    entryFee: 150,
    prizeFirst: 1000,
    prizeSecond: 800,
    teamSize: "Group",
    venue: "Entire Campus",
    date: "5th March",
  },
  {
    id: 10,
    name: "Attire Spectra",
    description: "Fashion competition with theme-based outfit display and judging.",
    category: "On-Ground",
    entryFee: 200,
    prizeFirst: 1000,
    prizeSecond: 800,
    teamSize: "Solo",
    venue: "Campus Grounds",
    date: "6th March",
  },
  // === SEMINAR HALL EVENTS - DRAMATICS ===
  {
    id: 11,
    name: "Skit",
    description: "Short comedic or dramatic theatrical performance by a group.",
    category: "On-Stage",
    entryFee: 500,
    prizeFirst: 1000,
    prizeSecond: 800,
    teamSize: "Group",
    venue: "Seminar Hall",
    date: "5th March",
  },
  {
    id: 12,
    name: "Mono Act",
    description: "Solo dramatic or comedic theatrical performance.",
    category: "On-Stage",
    entryFee: 50,
    prizeFirst: 500,
    prizeSecond: 250,
    teamSize: "Solo",
    venue: "Seminar Hall",
    date: "5th March",
  },
  {
    id: 13,
    name: "Swarsandhya",
    description: "Classical music and instrumental performance showcase.",
    category: "On-Stage",
    entryFee: 100,
    prizeFirst: 1000,
    prizeSecond: 500,
    teamSize: "Solo",
    venue: "Seminar Hall",
    date: "6th March",
  },
  // === LITERARY ARTS ===
  {
    id: 14,
    name: "Story Telling",
    description: "Captivating narration of original or classic stories with expression.",
    category: "Literary",
    entryFee: 50,
    prizeFirst: 500,
    prizeSecond: 250,
    teamSize: "Solo",
    venue: "Literary Hall",
    date: "5th March",
  },
  {
    id: 15,
    name: "Poem Recitation / Shayari",
    description: "Expressive recitation of poetry or traditional shayari.",
    category: "Literary",
    entryFee: 50,
    prizeFirst: 500,
    prizeSecond: 250,
    teamSize: "Solo",
    venue: "Literary Hall",
    date: "5th March",
  },
  {
    id: 16,
    name: "Stand-Up Comedy",
    description: "Humorous solo performance with original comedy material.",
    category: "Literary",
    entryFee: 100,
    prizeFirst: 1000,
    prizeSecond: 500,
    teamSize: "Solo",
    venue: "Comedy Club",
    date: "6th March",
  },
  // === FINE ARTS ===
  {
    id: 17,
    name: "Sketching / Doodling",
    description: "Artistic drawing competition with live or submitted artwork.",
    category: "Fine Arts",
    entryFee: 50,
    prizeFirst: 500,
    prizeSecond: 250,
    teamSize: "Solo",
    venue: "Art Gallery",
    date: "5th March",
  },
  {
    id: 18,
    name: "Mandala Art",
    description: "Creation of intricate mandala patterns with various art mediums.",
    category: "Fine Arts",
    entryFee: 50,
    prizeFirst: 500,
    prizeSecond: 250,
    teamSize: "Solo",
    venue: "Art Studio",
    date: "5th March",
  },
  {
    id: 19,
    name: "Rangoli",
    description: "Traditional Indian art form with colorful patterns and designs.",
    category: "Fine Arts",
    entryFee: 50,
    prizeFirst: 500,
    prizeSecond: 250,
    teamSize: "Solo",
    venue: "Art Courtyard",
    date: "6th March",
  },
  {
    id: 20,
    name: "Rellography",
    description: "Decorative paper art creating relief designs and patterns.",
    category: "Fine Arts",
    entryFee: 50,
    prizeFirst: 500,
    prizeSecond: 250,
    teamSize: "Solo",
    venue: "Art Studio",
    date: "5th March",
  },
  // === MISCELLANEOUS ===
  {
    id: 21,
    name: "Rose Day",
    description: "Celebration of friendship and bonds with rose exchange.",
    category: "On-Ground",
    entryFee: 50,
    prizeFirst: null,
    prizeSecond: null,
    teamSize: "Solo",
    venue: "Campus Grounds",
    date: "5th March",
  },
];
