// Mock events data for RHYTHMS 2026
// Complete event list organized chronologically by date (4-6 March 2026)

export const mockEvents = [
  // ═══════════════════════════════════════════════════════════
  // === 4TH MARCH 2026 - 9 EVENTS ===
  // ═══════════════════════════════════════════════════════════
  {
    id: 1,
    name: "Story Telling",
    description: "Spin a yarn",
    category: "On-Ground",
    entryFee: 0,
    prizeFirst: 500,
    prizeSecond: null,
    teamSize: "1-2",
    venue: "TBA",
    date: "4th March 2026",
    time: "10:00 am – 11:00 am",
  },
  {
    id: 2,
    name: "Poem Recitation",
    description: "Express with words",
    category: "On-Ground",
    entryFee: 0,
    prizeFirst: 500,
    prizeSecond: null,
    teamSize: "1",
    venue: "TBA",
    date: "4th March 2026",
    time: "11:00 am – 12:00 pm",
  },
  {
    id: 3,
    name: "Sketching",
    description: "Pencil magic",
    category: "Fine Arts",
    entryFee: 0,
    prizeFirst: 500,
    prizeSecond: null,
    teamSize: "1",
    venue: "TBA",
    date: "4th March 2026",
    time: "11:30 am – 01:00 pm",
  },
  {
    id: 4,
    name: "Treasure Hunt",
    description: "Find the clues",
    category: "On-Ground",
    entryFee: 0,
    prizeFirst: 1000,
    prizeSecond: null,
    teamSize: "4-6",
    venue: "Activity Area",
    date: "4th March 2026",
    time: "12:00 pm – 01:30 pm",
  },
  {
    id: 5,
    name: "Rangoli",
    description: "Colorful designs",
    category: "Fine Arts",
    entryFee: 0,
    prizeFirst: 500,
    prizeSecond: null,
    teamSize: "1-3",
    venue: "Activity Area",
    date: "4th March 2026",
    time: "12:00 pm – 02:00 pm",
  },
  {
    id: 6,
    name: "Attire Spectra",
    description: "Best dressed",
    category: "On-Ground",
    entryFee: 0,
    prizeFirst: 1000,
    prizeSecond: null,
    teamSize: "1",
    venue: "Activity Area",
    date: "4th March 2026",
    time: "01:30 pm – 02:30 pm",
  },
  {
    id: 7,
    name: "Reelography",
    description: "Reel making contest",
    category: "On-Ground",
    entryFee: 0,
    prizeFirst: 500,
    prizeSecond: null,
    teamSize: "2-4",
    venue: "Activity Area",
    date: "4th March 2026",
    time: "01:30 pm – 02:30 pm",
  },
  {
    id: 8,
    name: "Mandala Art",
    description: "Intricate patterns",
    category: "Fine Arts",
    entryFee: 0,
    prizeFirst: 500,
    prizeSecond: null,
    teamSize: "1",
    venue: "TBA",
    date: "4th March 2026",
    time: "02:00 pm – 03:00 pm",
  },
  {
    id: 9,
    name: "Short Film Competition",
    description: "Short film screening",
    category: "On-Ground",
    entryFee: 0,
    prizeFirst: 0,
    prizeSecond: null,
    teamSize: "3-5",
    venue: "Seminar Hall (Room No-125)",
    date: "4th March 2026",
    time: "02:00 pm onwards",
  },

  // ═══════════════════════════════════════════════════════════
  // === 5TH MARCH 2026 - 7 EVENTS ===
  // ═══════════════════════════════════════════════════════════
  {
    id: 10,
    name: "Rose Day",
    description: "Spread love",
    category: "On-Ground",
    entryFee: 0,
    prizeFirst: 0,
    prizeSecond: null,
    teamSize: "1",
    venue: "On Stage",
    date: "5th March 2026",
    time: "02:00 pm – 02:30 pm",
  },
  {
    id: 11,
    name: "Flashmob",
    description: "Surprise the crowd",
    category: "On-Ground",
    entryFee: 0,
    prizeFirst: 0,
    prizeSecond: null,
    teamSize: "6-12",
    venue: "On Ground",
    date: "5th March 2026",
    time: "02:30 pm – 03:00 pm",
  },
  {
    id: 12,
    name: "Antakshari",
    description: "Musical battle",
    category: "On-Ground",
    entryFee: 0,
    prizeFirst: 1500,
    prizeSecond: null,
    teamSize: "6-10",
    venue: "On Ground",
    date: "5th March 2026",
    time: "03:00 pm – 04:00 pm",
  },
  {
    id: 13,
    name: "Solo Singing",
    description: "Melodious voices",
    category: "On-Stage",
    entryFee: 0,
    prizeFirst: 1000,
    prizeSecond: null,
    teamSize: "1",
    venue: "On Stage",
    date: "5th March 2026",
    time: "04:00 pm – 05:30 pm",
  },
  {
    id: 14,
    name: "Duet Singing",
    description: "Harmonize together",
    category: "On-Stage",
    entryFee: 0,
    prizeFirst: 1000,
    prizeSecond: null,
    teamSize: "2",
    venue: "On Stage",
    date: "5th March 2026",
    time: "04:00 pm – 05:30 pm",
  },
  {
    id: 15,
    name: "Solo Dance",
    description: "Showcase your solo moves",
    category: "On-Stage",
    entryFee: 0,
    prizeFirst: 1000,
    prizeSecond: null,
    teamSize: "1",
    venue: "On Stage",
    date: "5th March 2026",
    time: "05:30 pm – 06:30 pm",
  },
  {
    id: 16,
    name: "Duet Dance",
    description: "Sync with your partner",
    category: "On-Stage",
    entryFee: 0,
    prizeFirst: 1000,
    prizeSecond: null,
    teamSize: "2",
    venue: "On Stage",
    date: "5th March 2026",
    time: "05:30 pm – 06:30 pm",
  },

  // ═══════════════════════════════════════════════════════════
  // === 6TH MARCH 2026 - 5 EVENTS ===
  // ═══════════════════════════════════════════════════════════
  {
    id: 17,
    name: "Swarsandhya",
    description: "Classical / semi-classical singing",
    category: "On-Stage",
    entryFee: 0,
    prizeFirst: 0,
    prizeSecond: null,
    teamSize: "1",
    venue: "Seminar Hall (Room No-125)",
    date: "6th March 2026",
    time: "11:00 am – 12:30 pm",
  },
  {
    id: 18,
    name: "Dramatics / Skit",
    description: "Short play",
    category: "On-Stage",
    entryFee: 0,
    prizeFirst: 1000,
    prizeSecond: null,
    teamSize: "3-8",
    venue: "Seminar Hall (Room No-125)",
    date: "6th March 2026",
    time: "02:00 pm – 02:30 pm",
  },
  {
    id: 19,
    name: "Mono Act",
    description: "One person act",
    category: "On-Stage",
    entryFee: 0,
    prizeFirst: 500,
    prizeSecond: null,
    teamSize: "1",
    venue: "Seminar Hall (Room No-125)",
    date: "6th March 2026",
    time: "02:00 pm – 02:30 pm",
  },
  {
    id: 20,
    name: "Group Dance",
    description: "Ideally 6–12 members",
    category: "On-Stage",
    entryFee: 0,
    prizeFirst: 3000,
    prizeSecond: null,
    teamSize: "6-12",
    venue: "On Stage",
    date: "6th March 2026",
    time: "04:30 pm – 06:00 pm",
  },
  {
    id: 21,
    name: "Fashion Show",
    description: "Walk the ramp",
    category: "On-Stage",
    entryFee: 0,
    prizeFirst: 7000,
    prizeSecond: null,
    teamSize: "8-12",
    venue: "On Stage",
    date: "6th March 2026",
    time: "06:00 pm – 07:30 pm",
  },
];

